easy_admin:
    site_name: 'Ecommerce'
    entities:
        # List the entity class name you want to manage
#        - App\Entity\Category
#        - App\Entity\User
        Product:
            class: App\Entity\Product
            form:
                fields:
                    - 'name'
                    - 'slug'
                    - 'description'
                    - 'price'
                    - 'date'
                    - 'coeur'
                    - {property: 'image', type: 'file'}
                    - 'promotion'
                    - 'category'

        Category:
            class: App\Entity\Category

        User:
            class: App\Entity\User